---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: front-end-ingressroute
  labels:
    name: front-end
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`sockshop.apps.argoproj.io`)
    services:
    - kind: Service
      name: front-end
      port: 80
  tls: {}
